// Command rimegen generates typed table wrappers and direct field accessors.
// It uses only the Go standard library and reads Go files in the current package.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"reflect"
	"strconv"
	"strings"
)

type field struct{ name, logical, typ, kind string }

func main() {
	typeName := flag.String("type", "", "record struct to generate")
	output := flag.String("output", "zz_rime.gen.go", "generated Go file")
	flag.Parse()
	if *typeName == "" {
		fail("-type is required")
	}
	if err := generate(*typeName, *output); err != nil {
		fail("%v", err)
	}
}

func generate(typeName, output string) error {
	entries, err := os.ReadDir(".")
	if err != nil {
		return err
	}
	fs := token.NewFileSet()
	var files []*ast.File
	specs := map[string]ast.Expr{}
	pkg := ""
	for _, entry := range entries {
		name := entry.Name()
		if entry.IsDir() || !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") || name == filepath.Base(output) {
			continue
		}
		f, err := parser.ParseFile(fs, name, nil, parser.ParseComments)
		if err != nil {
			return err
		}
		if pkg == "" {
			pkg = f.Name.Name
		} else if pkg != f.Name.Name {
			continue
		}
		files = append(files, f)
		for _, decl := range f.Decls {
			g, ok := decl.(*ast.GenDecl)
			if !ok || g.Tok.String() != "type" {
				continue
			}
			for _, s := range g.Specs {
				ts := s.(*ast.TypeSpec)
				specs[ts.Name.Name] = ts.Type
			}
		}
	}
	if pkg == "" {
		return fmt.Errorf("no Go package found in current directory")
	}
	var st *ast.StructType
	for _, f := range files {
		for _, d := range f.Decls {
			g, ok := d.(*ast.GenDecl)
			if !ok {
				continue
			}
			for _, s := range g.Specs {
				ts := s.(*ast.TypeSpec)
				if ts.Name.Name == typeName {
					st, _ = ts.Type.(*ast.StructType)
				}
			}
		}
	}
	if st == nil {
		return fmt.Errorf("%s is not a struct declared in the current package", typeName)
	}
	var fields []field
	var key *field
	for _, f := range st.Fields.List {
		if len(f.Names) == 0 || f.Tag == nil || !ast.IsExported(f.Names[0].Name) {
			continue
		}
		tagText, err := strconv.Unquote(f.Tag.Value)
		if err != nil {
			return err
		}
		tag := reflectTag(tagText)
		if tag["-"] != "" {
			continue
		}
		var typ bytes.Buffer
		if err := format.Node(&typ, fs, f.Type); err != nil {
			return err
		}
		logical := tag["name"]
		if logical == "" {
			logical = f.Names[0].Name
		}
		fd := field{name: f.Names[0].Name, logical: logical, typ: typ.String(), kind: underlying(f.Type, specs, map[string]bool{})}
		if tag["primary"] != "" {
			key = &fd
		}
		if comparable(f.Type, specs, map[string]bool{}) {
			fields = append(fields, fd)
		}
	}
	if key == nil {
		return fmt.Errorf("%s has no rime primary field", typeName)
	}
	if !comparable(parseExpr(key.typ), specs, map[string]bool{}) {
		return fmt.Errorf("primary key %s is not comparable", key.name)
	}
	var src strings.Builder
	fmt.Fprintf(&src, "// Code generated by rimegen; DO NOT EDIT.\npackage %s\n\nimport \"github.com/marcgauthier/murmur/rime\"\n\n", pkg)
	fmt.Fprintf(&src, "type %sRimeFields struct {\n", typeName)
	for _, f := range fields {
		fmt.Fprintf(&src, "%s %s\n", f.name, fieldType(typeName, f))
	}
	fmt.Fprintf(&src, "}\n\ntype %sRimeTable struct { *rime.Table[%s]; Fields %sRimeFields }\n\n", typeName, typeName, typeName)
	fmt.Fprintf(&src, "func Register%s(db *rime.DB, opts ...rime.TableOption[%s]) (*%sRimeTable, error) {\n", typeName, typeName, typeName)
	fmt.Fprintf(&src, "t, err := rime.Register[%s](db, opts...); if err != nil { return nil, err }; return &%sRimeTable{Table:t, Fields:%sRimeFields{\n", typeName, typeName, typeName)
	for _, f := range fields {
		fmt.Fprintf(&src, "%s: rime.%s%s(t, %q, func(v *%s) %s { return v.%s }),\n", f.name, constructor(f), constructorArgs(typeName, f), f.logical, typeName, f.typ, f.name)
	}
	fmt.Fprintf(&src, "}}, nil\n}\n\n")
	fmt.Fprintf(&src, "func (t *%sRimeTable) Get(key %s) (*%s, error) { return t.Table.Get(key) }\n", typeName, key.typ, typeName)
	fmt.Fprintf(&src, "func (t *%sRimeTable) Lookup(key %s) (*%s, bool, error) { return t.Table.Lookup(key) }\n", typeName, key.typ, typeName)
	fmt.Fprintf(&src, "func (t *%sRimeTable) Update(key %s, fn func(*%s) error) error { return t.Table.Update(key, fn) }\n", typeName, key.typ, typeName)
	fmt.Fprintf(&src, "func (t *%sRimeTable) Delete(key %s) error { return t.Table.Delete(key) }\n", typeName, key.typ)
	fmt.Fprintf(&src, "func (t *%sRimeTable) DeleteMany(keys []%s) error { anyKeys := make([]any, len(keys)); for i := range keys { anyKeys[i] = keys[i] }; return t.Table.DeleteMany(anyKeys) }\n", typeName, key.typ)
	formatted, err := format.Source([]byte(src.String()))
	if err != nil {
		return fmt.Errorf("format generated code: %w", err)
	}
	return os.WriteFile(output, formatted, 0644)
}

func reflectTag(raw string) map[string]string {
	out := map[string]string{}
	q := reflect.StructTag(raw).Get("rime")
	for _, x := range strings.Split(q, ",") {
		k, v, ok := strings.Cut(x, "=")
		if !ok {
			out[k] = "1"
		} else {
			out[k] = v
		}
	}
	return out
}

func parseExpr(s string) ast.Expr { e, _ := parser.ParseExpr(s); return e }
func fieldType(t string, f field) string {
	switch f.kind {
	case "string":
		if f.typ == "string" {
			return "rime.StringField[" + t + "]"
		}
	case "bool":
		if f.typ == "bool" {
			return "rime.BoolField[" + t + "]"
		}
	}
	return "rime.Field[" + t + ", " + f.typ + "]"
}
func constructor(f field) string {
	switch f.kind {
	case "string":
		if f.typ == "string" {
			return "StringFieldFrom"
		}
	case "bool":
		if f.typ == "bool" {
			return "BoolFieldFrom"
		}
	case "number":
		return "NumericFieldFrom"
	}
	return "FieldFrom"
}
func constructorArgs(t string, f field) string {
	if f.kind == "string" && f.typ == "string" || f.kind == "bool" && f.typ == "bool" {
		return "[" + t + "]"
	}
	return "[" + t + ", " + f.typ + "]"
}

func underlying(e ast.Expr, specs map[string]ast.Expr, seen map[string]bool) string {
	switch x := e.(type) {
	case *ast.Ident:
		if x.Name == "string" || x.Name == "bool" {
			return x.Name
		}
		if isNumber(x.Name) {
			return "number"
		}
		if seen[x.Name] {
			return "other"
		}
		seen[x.Name] = true
		if t, ok := specs[x.Name]; ok {
			return underlying(t, specs, seen)
		}
	case *ast.ArrayType:
		return "other"
	}
	return "other"
}
func isNumber(s string) bool {
	return strings.Contains(" int int8 int16 int32 int64 uint uint8 uint16 uint32 uint64 float32 float64 ", " "+s+" ")
}
func comparable(e ast.Expr, specs map[string]ast.Expr, seen map[string]bool) bool {
	switch x := e.(type) {
	case *ast.Ident:
		if x.Name == "string" || x.Name == "bool" || isNumber(x.Name) {
			return true
		}
		if seen[x.Name] {
			return true
		}
		seen[x.Name] = true
		if t, ok := specs[x.Name]; ok {
			return comparable(t, specs, seen)
		}
		return false
	case *ast.StarExpr, *ast.ChanType:
		return true
	case *ast.ArrayType:
		return comparable(x.Elt, specs, seen)
	case *ast.StructType:
		for _, f := range x.Fields.List {
			if !comparable(f.Type, specs, seen) {
				return false
			}
		}
		return true
	case *ast.InterfaceType:
		return true
	}
	return false
}
func fail(s string, args ...any) { fmt.Fprintf(os.Stderr, "rimegen: "+s+"\n", args...); os.Exit(2) }
